#!/bin/sh
#concatenate files to make an html

main() {

	ofile='../04.html'

	#remove old output file, if present
		if [ -f $ofile ]; then
			rm $ofile
			fi

			printf '<!DOCTYPE html>' >> "$ofile"
			printf '<html lang="en"><head>' >> "$ofile"
			printf '\n<meta name="viewport" content="width=device-width, initial-scale=1">' >> "$ofile"
			printf '\n<title>Heat, Ventillation, A/C (hvac)</title>' >> "$ofile"

			printf '\n<style>' >> "$ofile"
			
			#try a table wrapper to help it scroll
			printf '\n\t.scrollWrapper {' >> "$ofile"
				printf '\n\t\toverflow-x: auto;' >> "$ofile"
				printf '\n\t\twhite-space: nowrap;' >> "$ofile" #or else it might wrap in a cell a lot and not scroll
				printf '\n\t\tborder: none;' >> "$ofile"
				printf '\n\t}' >> "$ofile"


			printf '\n\ttable {' >> "$ofile"
				printf '\n\t\tborder-collapse: collapse;' >> "$ofile"
				printf '\n\t\tborder-spacing: 0;' >> "$ofile"
				printf '\n\t\twidth: 100%%;' >> "$ofile"
				printf '\n\t\tborder: 2px solid #ddd;' >> "$ofile"
			printf '\n\t}' >> "$ofile"

			printf '\n\tth {' >> "$ofile"
				printf '\n\t\ttext-align: center;' >> "$ofile"
				#printf '\n\t\tpadding: 8px;' >> "$ofile"
				printf '\n\t\tborder: 2px solid #ddd;' >> "$ofile"
			printf '\n\t}' >> "$ofile"

			printf '\n\ttd {' >> "$ofile"
				printf '\n\t\ttext-align: left;' >> "$ofile"
				printf '\n\t\tpadding: 8px;' >> "$ofile"
				printf '\n\t\tborder: 2px solid #ddd;' >> "$ofile"
			printf '\n\t}' >> "$ofile"

			printf '\n\tdiv {' >> "$ofile"
				printf '\n\t\tborder: 1px solid red;' >> "$ofile"
			printf '\n\t}' >> "$ofile"


			printf '\n\t.scroll-box {' >> "$ofile"
    			printf '\n\t\tmax-height: 200px;' >> "$ofile"
    			printf '\n\t\toverflow-y: auto;' >> "$ofile"
    			printf '\n\t\tborder: 1px solid #ccc;' >> "$ofile"
    			printf '\n\t\tpadding: 10px;' >> "$ofile"
    			printf '\n\t\tbackground-color: #f9f9f9;' >> "$ofile"
			printf '\n\t}' >> "$ofile"


			printf '\n</style>' >> "$ofile"

			printf '\n</head><body>' >> "$ofile"
			printf '\n<h2>Heat, Ventillation, and A/C (HVAC)</h2>' >> "$ofile"


			cat '02-front' >> $ofile
			printf '\n\n<br><hr><br>\n\n' >> $ofile
			cat '03-ofc1' >> $ofile
			printf '\n\n<br><hr><br>\n\n' >> $ofile
			cat '04-ofc2' >> $ofile
			printf '\n\n<br><hr><br>\n\n' >> $ofile
			cat '05-rm1' >> $ofile
			printf '\n\n<br><hr><br>\n\n' >> $ofile
			cat '06-rm4' >> $ofile
			printf '\n\n<br><hr><br>\n\n' >> $ofile
			cat '07-nursery' >> $ofile
			printf '\n\n<br><hr><br>\n\n' >> $ofile
			cat '08-wc' >> $ofile
			printf '\n\n<br><hr><br>\n\n' >> $ofile
			cat '09-modA' >> $ofile
			printf '\n\n<br><hr><br>\n\n' >> $ofile
			cat '10-modB' >> $ofile
			printf '\n\n<br><hr><br>\n\n' >> $ofile
			cat '11-modC' >> $ofile
			printf '\n\n<br><hr><br>\n\n' >> $ofile

			#javascript
				printf '\n<script>' >> $ofile
				cat 13-globals.js >> $ofile
				cat 14-listeners.js >> $ofile
				cat 15-select1.js >> $ofile
				cat 17-readTables.js >> $ofile
				cat 19-mkJsonFile.js >> $ofile
				cat 20-copyClipboard.js	>> $ofile
				printf '\n</script>' >> $ofile

	printf '</body></html>' >> "$ofile"


#	case "$1" in
#		"m") #manual concatenante		
#			printf '\nnot implemented'
#			;;
#		"ac") #automated concatenate
#			printf '\noption ac deactivated due to not knowing how to operate find -regex'
#
#			#decided to hardcode instead of find due to delay getting the correct regex
#				#files==$(find . -type f -regex '\./[0-9][0-9].*') #output with =
#				#files=$(find . -regextype posix-basic -regex '\./.[[:digit:]]*') #no output
#				#files==$(find . -type f -regex '^\d\d.*') #no output
#				#files==$(find . -type f -regex  '\d{2}.*') #no output
#				#files==$(find . -type f -regex  '([1-9]|1[0-2])-.*') #no output
#				#files==$(find . -type f -regex  '0[0-2]-.*') #no output
#			#printf '\ndebug files=%s' $files
#
#			#subsort=$(printf '%s' "$files" | sort)
#			#for i in $subsort; do
#			#	printf '\ndebug files again%s' $i
#			#	#printf '\n\n' >> "$i"
#			#	#cat "$i" >> "$ofile"
#			#done
#			;;
#		*)
#			printf '\nunexpected choice / case %s. Expected ./0 c    ..... exiting' "$choice"; exit 1
#		;;
#	esac

}


main "$@"; exit 0
